-- MySQL Script generated by MySQL Workbench
-- Tue Feb 18 22:30:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bagginsDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bagginsDB` ;

-- -----------------------------------------------------
-- Schema bagginsDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bagginsDB` DEFAULT CHARACTER SET utf8 ;
USE `bagginsDB` ;

-- -----------------------------------------------------
-- Table `bagginsDB`.`TipoPessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bagginsDB`.`TipoPessoa` ;

CREATE TABLE IF NOT EXISTS `bagginsDB`.`TipoPessoa` (
  `id` INT NOT NULL,
  `usuario` INT NOT NULL DEFAULT 1 COMMENT 'Tipo que representa Pessoa como um usuario',
  `usuarioEmpresa` INT NOT NULL DEFAULT 2 COMMENT 'Tipo que representa pessoa como uma empresa e usuário ao mesmo tempo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Usuario_UNIQUE` (`usuario` ASC),
  UNIQUE INDEX `Empresa_UNIQUE` (`usuarioEmpresa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagginsDB`.`Contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bagginsDB`.`Contato` ;

CREATE TABLE IF NOT EXISTS `bagginsDB`.`Contato` (
  `id` INT NOT NULL,
  `pais` VARCHAR(3) NULL,
  `ddd` INT NULL,
  `numero` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagginsDB`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bagginsDB`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `bagginsDB`.`Pessoa` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `idTipoPessoa` INT NOT NULL,
  `idContato` INT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `idTipoPessoa`, `idContato`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_PESSOA_TIPO_PESSOA1_idx` (`idTipoPessoa` ASC),
  INDEX `fk_PESSOA_CONTATO1_idx` (`idContato` ASC),
  CONSTRAINT `fk_PESSOA_TIPO_PESSOA1`
    FOREIGN KEY (`idTipoPessoa`)
    REFERENCES `bagginsDB`.`TipoPessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESSOA_CONTATO1`
    FOREIGN KEY (`idContato`)
    REFERENCES `bagginsDB`.`Contato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bagginsDB`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bagginsDB`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `bagginsDB`.`Endereco` (
  `id` INT NOT NULL,
  `cep` INT NOT NULL,
  `numero` INT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`id`, `idPessoa`),
  INDEX `fk_ENDERECO_PESSOA1_idx` (`idPessoa` ASC),
  CONSTRAINT `fk_ENDERECO_PESSOA1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `bagginsDB`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagginsDB`.`Oportunidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bagginsDB`.`Oportunidade` ;

CREATE TABLE IF NOT EXISTS `bagginsDB`.`Oportunidade` (
  `id` INT NOT NULL,
  `nomeOportunidade` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `idPessoa` INT NOT NULL,
  `idTipoPessoa` INT NOT NULL,
  `idContato` INT NOT NULL,
  PRIMARY KEY (`id`, `idPessoa`, `idTipoPessoa`, `idContato`),
  INDEX `fk_OPORTUNIDADE_PESSOA1_idx` (`idPessoa` ASC, `idTipoPessoa` ASC, `idContato` ASC),
  CONSTRAINT `fk_OPORTUNIDADE_PESSOA1`
    FOREIGN KEY (`idPessoa` , `idTipoPessoa` , `idContato`)
    REFERENCES `bagginsDB`.`Pessoa` (`id` , `idTipoPessoa` , `idContato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagginsDB`.`Idioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bagginsDB`.`Idioma` ;

CREATE TABLE IF NOT EXISTS `bagginsDB`.`Idioma` (
  `id` INT NOT NULL,
  `nomeIdioma` VARCHAR(45) NOT NULL,
  `instituicao` VARCHAR(100) NOT NULL,
  `duracao` INT NOT NULL,
  `dtConclusão` DATETIME NOT NULL,
  `nivel` INT NOT NULL COMMENT '0 - Basico\n1 - Intermediario\n2 - Avançado\n3 - Fluente\n4 - Nativo',
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`id`, `idPessoa`),
  INDEX `fk_IDIOMA_PESSOA1_idx` (`idPessoa` ASC),
  CONSTRAINT `fk_IDIOMA_PESSOA1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `bagginsDB`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagginsDB`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bagginsDB`.`Curso` ;

CREATE TABLE IF NOT EXISTS `bagginsDB`.`Curso` (
  `id` INT NOT NULL COMMENT '		',
  `nomeCurso` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(450) NOT NULL,
  `instituicao` VARCHAR(100) NOT NULL,
  `dtConclusao` DATETIME NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`id`, `idPessoa`),
  INDEX `fk_CURSO_PESSOA1_idx` (`idPessoa` ASC),
  CONSTRAINT `fk_CURSO_PESSOA1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `bagginsDB`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagginsDB`.`FormacaoEscolar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bagginsDB`.`FormacaoEscolar` ;

CREATE TABLE IF NOT EXISTS `bagginsDB`.`FormacaoEscolar` (
  `id` INT NOT NULL,
  `curso` VARCHAR(100) NOT NULL,
  `instituicao` VARCHAR(100) NOT NULL,
  `grauEscola` INT NOT NULL COMMENT '0 - Sem Formação\n1 - Basico\n2 - Medio Incompleto\n3 - Medio completo\n4 - Superior incompleto\n5 - Superior cursando\n6 - Superior completo\n7 - Pos Graduação incompleta\n8 - Pos Graduação cursando\n9 - Pos Graduação completa\n10 - Mestrado Incompleto\n11 - Mestrado Cursando\n12 - Mestrado Completo\n13 - Doutorado Incompleto\n14 - Doutorado Cursando\n15 - Doutorado Completo\n',
  `dtConclusao` DATETIME NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`id`, `idPessoa`),
  INDEX `fk_FORMACAO_ESCOLAR_PESSOA1_idx` (`idPessoa` ASC),
  CONSTRAINT `fk_FORMACAO_ESCOLAR_PESSOA1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `bagginsDB`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagginsDB`.`ExperienciaProfissional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bagginsDB`.`ExperienciaProfissional` ;

CREATE TABLE IF NOT EXISTS `bagginsDB`.`ExperienciaProfissional` (
  `id` INT NOT NULL,
  `empresa` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(400) NOT NULL,
  `dtAdmissao` DATETIME NOT NULL,
  `dtDemissao` VARCHAR(45) NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`id`, `idPessoa`),
  INDEX `fk_EXPERIENCIA_PROFISSIONAL_PESSOA1_idx` (`idPessoa` ASC),
  CONSTRAINT `fk_EXPERIENCIA_PROFISSIONAL_PESSOA1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `bagginsDB`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagginsDB`.`Curriculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bagginsDB`.`Curriculo` ;

CREATE TABLE IF NOT EXISTS `bagginsDB`.`Curriculo` (
  `id` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `idIdioma` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `idFormacaoEscola` INT NOT NULL,
  `idExperienciaProfissional` INT NOT NULL,
  PRIMARY KEY (`id`, `idPessoa`, `idIdioma`, `idCurso`, `idFormacaoEscola`, `idExperienciaProfissional`),
  INDEX `fk_CURRICULO_PESSOA1_idx` (`idPessoa` ASC),
  INDEX `fk_CURRICULO_IDIOMA1_idx` (`idIdioma` ASC),
  INDEX `fk_CURRICULO_CURSO1_idx` (`idCurso` ASC),
  INDEX `fk_CURRICULO_FORMACAO_ESCOLAR1_idx` (`idFormacaoEscola` ASC),
  INDEX `fk_CURRICULO_EXPERIENCIA_PROFISSIONAL1_idx` (`idExperienciaProfissional` ASC),
  CONSTRAINT `fk_CURRICULO_PESSOA1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `bagginsDB`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURRICULO_IDIOMA1`
    FOREIGN KEY (`idIdioma`)
    REFERENCES `bagginsDB`.`Idioma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURRICULO_CURSO1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `bagginsDB`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURRICULO_FORMACAO_ESCOLAR1`
    FOREIGN KEY (`idFormacaoEscola`)
    REFERENCES `bagginsDB`.`FormacaoEscolar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURRICULO_EXPERIENCIA_PROFISSIONAL1`
    FOREIGN KEY (`idExperienciaProfissional`)
    REFERENCES `bagginsDB`.`ExperienciaProfissional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bagginsDB`.`Candidatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bagginsDB`.`Candidatura` ;

CREATE TABLE IF NOT EXISTS `bagginsDB`.`Candidatura` (
  `id` INT NOT NULL,
  `idCurriculo` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `idOportunidade` INT NOT NULL,
  PRIMARY KEY (`id`, `idCurriculo`, `idPessoa`, `idOportunidade`),
  INDEX `fk_CANDIDATURA_CURRICULO1_idx` (`idCurriculo` ASC, `idPessoa` ASC),
  INDEX `fk_CANDIDATURA_OPORTUNIDADE1_idx` (`idOportunidade` ASC),
  CONSTRAINT `fk_CANDIDATURA_CURRICULO1`
    FOREIGN KEY (`idCurriculo` , `idPessoa`)
    REFERENCES `bagginsDB`.`Curriculo` (`id` , `idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CANDIDATURA_OPORTUNIDADE1`
    FOREIGN KEY (`idOportunidade`)
    REFERENCES `bagginsDB`.`Oportunidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
