insert into idioma (idioma) values ("Africâner"),
("Akan"),
("Albanês"),
("Amárico"),
("Árabe"),
("Armênio"),
("Língua de sinais americana"),
("Assamês"),
("Assírio"),
("Azeri"),
("Curmânji"),
("Bambara"),
("Bashkir"),
("Basco"),
("Bielo-russo"),
("Bengalês"),
("Bósnio"),
("Bravanês"),
("Búlgaro"),
("Birmanês"),
("Cambojano"),
("Cantonês"),
("Catalão"),
("Cebuano"),
("Chaldean"),
("Chamorro"),
("Chaozhou"),
("Chavacano"),
("Chin"),
("Chuquês"),
("Cree"),
("Croata"),
("Tcheco"),
("Dacota"),
("Dinamarquês"),
("Dari"),
("Dinka"),
("Dioula"),
("Holandês"),
("Butanês"),
("Inglês"),
("Estoniano"),
("Ewe"),
("Fanti"),
("Faroês"),
("Farsi"),
("Hindi fijiano"),
("Finlandês"),
("Flamengo"),
("Francês"),
("Franco-canadense"),
("Frísio"),
("Fujianês"),
("Fujian"),
("Fula"),
("Fulani"),
("Fuzhou"),
("Ga"),
("Gaélico"),
("Galego"),
("Ganda"),
("Georgiano"),
("Alemão"),
("Gorani"),
("Grego"),
("Gujarati"),
("Haitiano"),
("Hacá"),
("Hassaniya"),
("Hauçá"),
("Hebraico"),
("Hiligaynon"),
("Hindi"),
("Hmong"),
("Húngaro"),
("Ibanag"),
("Islandês"),
("Igbo"),
("Ilocano"),
("Ilonggo"),
("Indiano"),
("Indonésio"),
("Inuktitut"),
("Irlandês"),
("Italiano"),
("Jakartanese"),
("Japonês"),
("Javanês"),
("Canjobal"),
("Canarês"),
("Karen"),
("Caxemira"),
("Cazaque"),
("Khalkha"),
("Khmer"),
("Kikuyu"),
("Quiniaruanda"),
("Kirundi"),
("Coreano"),
("Kosovo"),
("Kotokoli"),
("Krio"),
("Curdo"),
("Curmânji"),
("Quirguiz"),
("Lakota"),
("Laociano"),
("Latim"),
("Letão"),
("Lingala"),
("Lituano"),
("Luganda"),
("Luo"),
("Lusoga"),
("Luxemburguês"),
("Maay"),
("Macedônio"),
("Malgaxe"),
("Malaio"),
("Malaiala"),
("Maldivense"),
("Maltês"),
("Mandarim"),
("Mandinga"),
("Mandinka"),
("Maori"),
("Marata"),
("Marshalês"),
("Mien"),
("Mirpuri"),
("Mixteco"),
("Moldovan"),
("Mongol"),
("Navajo"),
("Napolitano"),
("Nepali"),
("Norueguês"),
("Nuer"),
("Nianja"),
("Ojíbua"),
("Oriá"),
("Oromo"),
("Osseta"),
("Pahari"),
("Pampangan"),
("Pachto"),
("Patoá"),
("Inglês pidgin"),
("Polonês"),
("Português"),
("Pothwari"),
("Pulaar"),
("Punjabi"),
("Putian"),
("Guanxi"),
("Quechua"),
("Romani"),
("Romeno"),
("Romanche"),
("Rundi"),
("Russo"),
("Samoano"),
("Sango"),
("Sânscrito"),
("Sérvio"),
("Xangainês"),
("Chona"),
("Sichuan"),
("Siciliano"),
("Sindi"),
("Cingalês"),
("Cingalês"),
("Suázi/suazilandês"),
("Eslovaco"),
("Esloveno"),
("Somali"),
("Soninquê"),
("Sorâni"),
("Soto do sul"),
("Espanhol"),
("Sundanês"),
("Susu"),
("Suaíle"),
("Sueco"),
("Sylheti"),
("Tagalog"),
("Taiwanês"),
("Tadjique"),
("Tâmil"),
("Telugu"),
("Tailandês"),
("Tibetano"),
("Tigrínia"),
("Tonga"),
("Tshiluba"),
("Tsonga"),
("Tswana"),
("Turco"),
("Turcomeno"),
("Uigur"),
("Ucraniano"),
("Urdu"),
("Uzbeque"),
("Venda"),
("Vietnamita"),
("Visayan"),
("Galês"),
("Uolofe"),
("Xhosa"),
("Yao"),
("Iídiche"),
("Iorubá"),
("Yupik"),
("Zulu");


insert into idioma_proficiencia (proficiencia) values ('Iniciante'), ('Intermediário'), ('Fluente');


insert into habilidade (habilidade) values ("Jardinagem"),
("Ajuda em Cultivos e Colheitas"),
("Bartender"),
("Consertos Gerais"),
("Recepção"),
("Administração"),
("Desenvolvimento Web"),
("Mídias Sociais"),
("Ensinar Idiomas"),
("Pintura e Decoração"),
("Tarefas Domésticas"),
("Ajuda na Limpeza"),
("Organizar eventos e festas"),
("Guia Local"),
("Trabalho Social"),
("Fotografia"),
("Música"),
("Preparar Refeições"),
("Ajudante de Cozinha"),
("Produção de vídeo"),
("Ensinar Esportes"),
("Turno da Noite"),
("Cuidado de Crianças"),
("Cuidado de Animais");


