use bagginsdb;

insert into idioma (id, idioma) values (0, "--Selecione--");

insert into idioma (idioma) values ("Africâner"),
("Akan"),
("Albanês"),
("Amárico"),
("Árabe"),
("Armênio"),
("Língua de sinais americana"),
("Assamês"),
("Assírio"),
("Azeri"),
("Curmânji"),
("Bambara"),
("Bashkir"),
("Basco"),
("Bielo-russo"),
("Bengalês"),
("Bósnio"),
("Bravanês"),
("Búlgaro"),
("Birmanês"),
("Cambojano"),
("Cantonês"),
("Catalão"),
("Cebuano"),
("Chaldean"),
("Chamorro"),
("Chaozhou"),
("Chavacano"),
("Chin"),
("Chuquês"),
("Cree"),
("Croata"),
("Tcheco"),
("Dacota"),
("Dinamarquês"),
("Dari"),
("Dinka"),
("Dioula"),
("Holandês"),
("Butanês"),
("Inglês"),
("Estoniano"),
("Ewe"),
("Fanti"),
("Faroês"),
("Farsi"),
("Hindi fijiano"),
("Finlandês"),
("Flamengo"),
("Francês"),
("Franco-canadense"),
("Frísio"),
("Fujianês"),
("Fujian"),
("Fula"),
("Fulani"),
("Fuzhou"),
("Ga"),
("Gaélico"),
("Galego"),
("Ganda"),
("Georgiano"),
("Alemão"),
("Gorani"),
("Grego"),
("Gujarati"),
("Haitiano"),
("Hacá"),
("Hassaniya"),
("Hauçá"),
("Hebraico"),
("Hiligaynon"),
("Hindi"),
("Hmong"),
("Húngaro"),
("Ibanag"),
("Islandês"),
("Igbo"),
("Ilocano"),
("Ilonggo"),
("Indiano"),
("Indonésio"),
("Inuktitut"),
("Irlandês"),
("Italiano"),
("Jakartanese"),
("Japonês"),
("Javanês"),
("Canjobal"),
("Canarês"),
("Karen"),
("Caxemira"),
("Cazaque"),
("Khalkha"),
("Khmer"),
("Kikuyu"),
("Quiniaruanda"),
("Kirundi"),
("Coreano"),
("Kosovo"),
("Kotokoli"),
("Krio"),
("Curdo"),
("Curmânji"),
("Quirguiz"),
("Lakota"),
("Laociano"),
("Latim"),
("Letão"),
("Lingala"),
("Lituano"),
("Luganda"),
("Luo"),
("Lusoga"),
("Luxemburguês"),
("Maay"),
("Macedônio"),
("Malgaxe"),
("Malaio"),
("Malaiala"),
("Maldivense"),
("Maltês"),
("Mandarim"),
("Mandinga"),
("Mandinka"),
("Maori"),
("Marata"),
("Marshalês"),
("Mien"),
("Mirpuri"),
("Mixteco"),
("Moldovan"),
("Mongol"),
("Navajo"),
("Napolitano"),
("Nepali"),
("Norueguês"),
("Nuer"),
("Nianja"),
("Ojíbua"),
("Oriá"),
("Oromo"),
("Osseta"),
("Pahari"),
("Pampangan"),
("Pachto"),
("Patoá"),
("Inglês pidgin"),
("Polonês"),
("Português|Brasil"),
("Português|Portugal"),
("Pothwari"),
("Pulaar"),
("Punjabi"),
("Putian"),
("Guanxi"),
("Quechua"),
("Romani"),
("Romeno"),
("Romanche"),
("Rundi"),
("Russo"),
("Samoano"),
("Sango"),
("Sânscrito"),
("Sérvio"),
("Xangainês"),
("Chona"),
("Sichuan"),
("Siciliano"),
("Sindi"),
("Cingalês"),
("Cingalês"),
("Suázi/suazilandês"),
("Eslovaco"),
("Esloveno"),
("Somali"),
("Soninquê"),
("Sorâni"),
("Soto do sul"),
("Espanhol"),
("Sundanês"),
("Susu"),
("Suaíle"),
("Sueco"),
("Sylheti"),
("Tagalog"),
("Taiwanês"),
("Tadjique"),
("Tâmil"),
("Telugu"),
("Tailandês"),
("Tibetano"),
("Tigrínia"),
("Tonga"),
("Tshiluba"),
("Tsonga"),
("Tswana"),
("Turco"),
("Turcomeno"),
("Uigur"),
("Ucraniano"),
("Urdu"),
("Uzbeque"),
("Venda"),
("Vietnamita"),
("Visayan"),
("Galês"),
("Uolofe"),
("Xhosa"),
("Yao"),
("Iídiche"),
("Iorubá"),
("Yupik"),
("Zulu");

insert into idioma_proficiencia (id, proficiencia) values (0, "--Selecione--");
insert into idioma_proficiencia (proficiencia) values ('Indefinido'), ('Iniciante'), ('Intermediário'), ('Fluente'), ('Nativo');


INSERT INTO `habilidade` VALUES (1,'Jardinagem','fa-seedling'),(2,'Ajuda em Cultivos e Colheitas','fa-tractor'),(3,'Bartender','fa-cocktail'),(4,'Consertos Gerais','fa-tools'),(5,'Recepção','fa-concierge-bell'),(6,'Administração','fa-users-cog'),(7,'Desenvolvimento Web','fa-laptop-code'),(8,'Mídias Sociais','fa-ad'),(9,'Ensinar Idiomas','fa-language'),(10,'Pintura e Decoração','fa-paint-roller'),(11,'Tarefas Domésticas','fa-bed'),(12,'Ajuda na Limpeza','fa-broom'),(13,'Organizar eventos e festas','fa-calendar'),(14,'Guia Local','fa-map'),(15,'Trabalho Social','fa-hands-helping'),(16,'Fotografia','fa-camera-retro'),(17,'Música','fa-music'),(18,'Preparar Refeições','fa-utensils'),(19,'Ajudante de Cozinha','fa-hamburger'),(20,'Produção de vídeo','fa-video'),(21,'Ensinar Esportes','fa-running'),(22,'Turno da Noite','fa-moon'),(23,'Cuidado de Crianças','fa-baby'),(24,'Cuidado de Animais','fa-paw');


INSERT INTO `oferta` 
VALUES 
(1,'Dormitório Privado','faLock'),
(2,'Quarto Compartilhado','faUsers'),
(3,'Camping','faCampground'),
(4,'Café da manhã','faCoffee'),
(5,'1 dia livre por semana','faUmbrellaBeach'),
(6,'2 dias livres por semana','faUmbrellaBeach'),
(7,'3 dias livres por semana','faUmbrellaBeach'),
(8,'Cozinha equipada','faUtensils'),
(9,'Descontos em tours/hospedagem','faPercent'),
(10,'Desconto com restaurantes','faPercent'),
(11,'Passeios de graça','faMapMarked'),
(12,'Carona na chegada','faCar'),
(13,'Bicicletas a vontade','faBicycle'),
(14,'Desconto em pubs e/ou festas','faGlassCheers'),
(15,'Certificado','faCertificate'),
(16,'Almoço','faDrumstickBite'),
(17,'Jantar','faHotdog'),
(18,'Aulas de Idiomas','faLanguage');


insert into tipo_oportunidade (tipo_oportunidade) values (""), ("ONG"),
("Empresa");
